server {
    listen 80;
    listen [::]:80;
    server_name vodka-casino.ru www.vodka-casino.ru;

    # Возвращаем 301 редирект на новый домен
    # Флаг $request_uri сохраняет путь страницы (если нужно)
    return 301 https://vod-ka.org$request_uri;
}
